//We need webpack and webpack cli

var webpack = require('webpack');
var path = require('path');

module.exports = {

    //debugging easier
    devtool:'inline-source-map',

entry:{
    'index':'./src/index.js'
},
mode:"development",

output:{
    //path.resolve and path.join
    //__dirname le full path dinxa
    path:path.resolve(__dirname,'dist'),
    filename:'main.js'
},
    //hot pack le only selective part lai reload garxa
    //Regular expression--powerful tool for prorgamming
module:{
    rules:[ //multiple rules //inside real different objects
        {//babel use garera es6, 7, es5, browser compatible
            //use babel on which files--all javascript files
            test:/\.js$/,   //regex start with // and end with $
            exclude:/node_modules/,
            use: 'babel-loader'

        }
    ]
},
    //devserver --- to serve the application, only in development

    //those content that are not generated by webpack
    devServer:{
        contentBase: path.join(__dirname,"public/"),
        port:3096,
        //HMR Reloading
        hot:true,
        //to serve webpack files
        publicPath: "http://localhost:3096/dist/"
    }
}